import scala.scalanative.unsafe._, stdio._

object Hello {
  def main(args: Array[String]): Unit = {
    throw new Exception()
  }
}
