li[34mTest run started[0m
liTest scala.scalanative.junit.[33mAssumeAfterException[0m.[36mtest[0m started
leTest scala.scalanative.junit.[33mAssumeAfterException[0m.[31mtest[0m failed: test throws, took <TIME>
e2scala.scalanative.junit.AssumeAfterException.test
leTest scala.scalanative.junit.[33mAssumeAfterException[0m.[31mtest[0m failed: Test could not be skipped due to other failures, took <TIME>
leCaused by: org.junit.AssumptionViolatedException: This assume should not pass
ldTest scala.scalanative.junit.[33mAssumeAfterException[0m.[36mtest[0m finished, took <TIME>
li[34mTest run finished: [0m[31m2 failed[0m[34m, [0m[34m0 ignored[0m[34m, 1 total, <TIME>[0m
d
