liTest run started
liTest scala.scalanative.junit.AssumeAfterException.test started
leTest scala.scalanative.junit.AssumeAfterException.test failed: test throws, took <TIME>
e2scala.scalanative.junit.AssumeAfterException.test
leTest scala.scalanative.junit.AssumeAfterException.test failed: Test could not be skipped due to other failures, took <TIME>
leCaused by: org.junit.AssumptionViolatedException: This assume should not pass
ldTest scala.scalanative.junit.AssumeAfterException.test finished, took <TIME>
liTest run finished: 2 failed, 0 ignored, 1 total, <TIME>
d
