ld[34mTest run [0mscala.scalanative.junit.[33mExceptionTest[0m[34m started[0m
ldTest scala.scalanative.junit.[33mExceptionTest[0m.[36mtest[0m started
leTest scala.scalanative.junit.[33mExceptionTest[0m.[31mtest[0m failed: java.lang.[31mIndexOutOfBoundsException[0m: Exception message, took <TIME>
e2scala.scalanative.junit.ExceptionTest.test
ldTest scala.scalanative.junit.[33mExceptionTest[0m.[36mtest[0m finished, took <TIME>
ld[34mTest run [0mscala.scalanative.junit.[33mExceptionTest[0m[34m finished: [0m[31m1 failed[0m[34m, [0m[34m0 ignored[0m[34m, 1 total, <TIME>[0m
d
